In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
# printをつけるとarray表記でなくなる
print(a)
# typeはndarray objectになります
print(type(a))
# 1次元配列3要素であることがわかる
a.shape

[1 2 3]
<class 'numpy.ndarray'>


(3,)

In [7]:
# 2次元配列を指定
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# 2×3行列であることが読み取れる
b.shape

(2, 3)

In [12]:
c1 = np.array([0,1,2,3,4,5])
# 変形(a×b行列に変換)
c2 = c1.reshape((2,3))
# reshapeは要素数が重要 = 要素数が合わない場合はエラーになります
# c2 = c1.reshape((3,4)) <- これはダメ
c2

array([[0, 1, 2],
       [3, 4, 5]])

#### 参照とコピー
- ravel:参照
- flatten:コピー

- 参照は変数に代入されたオブジェクトのメモリ上のアドレスを指します。
- コピーとは変数に代入されたオブジェクトを複製して新しいオブジェクトを作成することを指します。
- python標準のリストではスライスした結果はコピーが渡される
- Numpyでは、スライスの結果は参照が渡されるので注意！
- Pythonの標準リスト型では浅いコピーと深いコピーが区別される
- Numpyのcopyメソッドはオブジェクトを別に生成するので標準の深いコピーと同値であるとわかる

#### 浅いコピー　深いコピー
- pythonには2種類のコピーが存在
- 浅いコピー
    - オブジェクトのコピーを作成しますが、コピーされたオブジェクトの内部に含まれる他のオブジェクトについては、参照がコピー
    - 『深いコピー』とは、オブジェクトのコピーをすべて作成します。

In [13]:
# ravelメソッドは1次元配列に変換するメソッド
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [14]:
c4 = c2.flatten()
c4

array([0, 1, 2, 3, 4, 5])

In [19]:
# 浅いコピー
import copy
a = [1, 2, [3, 4, 5]]
b = a.copy()
print("1,2は新規オブジェクトが生成されるが[3,4,5]については、参照として複製")
print(a)
print(b)
# 深いコピー
c = copy.deepcopy(a)
print("deepcopyは全く同じオブジェクトを生成します")
print(a)
print(c)

1,2は新規オブジェクトが生成されるが[3,4,5]については、参照として複製
[1, 2, [3, 4, 5]]
[1, 2, [3, 4, 5]]
deepcopyは全く同じオブジェクトを生成します
[1, 2, [3, 4, 5]]
[1, 2, [3, 4, 5]]


In [69]:
a = np.array([1,2,3])
print(a)
# インデックスを指定してその要素を変更することができる
a[2] = 4
print(a)

b = np.array([[1,2,3],[4,5,6]])
print(b)
b[1,2] = 7 # 2行目の3番目の要素を置き換える
print(b)

[1 2 3]
[1 2 4]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 7]]


In [71]:
# 参照
a = np.array([1,2,3])
a1 = a
print(a1, a)
a1[1] = 5
# aの値を変えていないのにどちらの要素も変更されている
print(a1, a)

[1 2 3] [1 2 3]
[1 5 3] [1 5 3]


In [72]:
# コピー
a = np.array([1,2,3])
a2 = a.copy()
print(a2, a)
a2[0] = 100
# copyで生成したa2の値を変更してもaの行列はそのままになっている
print(a2, a)

[1 2 3] [1 2 3]
[100   2   3] [1 2 3]


In [74]:
c2 = np.array([[0,1,2],[3,4,5]])
c3 = c2.ravel()
c4 = c2.flatten()
print(c2, c3)
print(c2, c4)
c3[0] = 100 # c2をravelで1次元に戻したものは参照なので、元の行列に影響
c4[0] = 200 # c2をflattenで1次元に戻したものはコピーなので、元の行列に影響しない
print(c2, c3)
print(c2, c4)


[[0 1 2]
 [3 4 5]] [0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]] [0 1 2 3 4 5]
[[100   1   2]
 [  3   4   5]] [100   1   2   3   4   5]
[[100   1   2]
 [  3   4   5]] [200   1   2   3   4   5]


In [78]:
py_list1 = [0,1]
py_list2 = py_list1[:] # python標準のスライスはコピー
print(py_list1, py_list2)
py_list2[0] = 20
print(py_list1, py_list2)

print("=======================")
np_array1 = np.array([0,1])
np_array2 = np_array1[:] # Numpyのスライスは参照として生成
print(np_array1, np_array2)
np_array2[0] = 100
print(np_array1, np_array2)


[0, 1] [0, 1]
[0, 1] [20, 1]
[0 1] [0 1]
[100   1] [100   1]


In [21]:
a = np.array([1,2,3])
# windowsはnp.int32 linuxはnp.int64が割り当てられる
a.dtype

dtype('int64')

In [25]:
d = np.array([1,2], dtype=np.int16)
d.dtype


dtype('int16')

In [26]:
d.astype(np.float16)


array([1., 2.], dtype=float16)

In [28]:
# numpyの配列でもスライスは活用することができる
print(a)
print(a[0])
print(a[1:])
print(a[:-1])


[1 2 3]
1
[2 3]
[1 2]


In [67]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b[0])
print(b[1,0])
print(b[:2]) # <- この書き方だと普通のスライス
print(b[:,2])# <- ,2にすると全ての行の3番目の要素を抽出
print(b[1:])# <- 
print("#######")
print(b[2,:])# <- 2, = 2, = 2番目の行 = [7,8,9] :=全ての要素
# print(b[1,:,1]) <-　この指定方法は誤り
print("######")
print(b[0,1:]) # <- 0, = 0番目の行 = [1,2,3] 1: = 2つ目の要素以降
print(b[1: ,1]) # <- 1: = 1番目の行から最後の行 = [4,5,6],[7,8,9] ,1 = 各行の1番目 = 5,8
print("###################")
print(b[:,[0,2]]) # <- : = 全ての行 [0,2] = 1番目の要素と3番目の要素を取得


[1 2 3]
4
[[1 2 3]
 [4 5 6]]
[3 6 9]
[[4 5 6]
 [7 8 9]]
#######
[7 8 9]
######
[2 3]
[5 8]
###################
[[1 3]
 [4 6]
 [7 9]]


In [81]:
# 数列を返す
# 通常のfor文と指定の仕方が似ているところがあります
a = np.arange(10)
b = np.arange(1,11)
c = np.arange(1, 11, 2)
print(a)
print(b)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


#### 乱数
- 一様乱数：範囲の中からデータをランダムにピックアップするようなイメージです
    - np.random.Generator.random
- 正規分布乱数：正規分布に従った乱数を出力する方法がある
    - np.random.Generator.standard_normal

In [97]:
# random数値を返す
# 旧式generator, 最新generatorがありますが、今回は最新の方をレクチャー
rng = np.random.default_rng() # <- object生成
f = rng.random((3,2)) # m行 * n列という指定で 0<= x < 1までの数値を返す

rng2 = np.random.default_rng(123) # seed値を設定することで、randomで返却される値を固定できる
f2 = rng2.random((3,2))
print(f)
print(f2)

# 特定の範囲内の数値を生成
rng3 = np.random.default_rng(123)
f3 = rng3.integers(1,10) # 指定した範囲の数値から1つの値を返す
print(f3)

rng4 = np.random.default_rng(123)
# 第一引数、第二引数は省略可 default 0.0 <= x < 1.0
f4 = rng4.integers(1, 10, size=(3,3)) # 第一引数 <= x < 第二引数未満　でランダム整数値を size keyword引数でタプルを渡した行と列を生成
print(f4)

rng5 = np.random.default_rng(123)
# uniformを設定すると返却値がfloatになる
f5 = rng.uniform(0.0, 5.0, size=(2,3))
print(f5)
f6 = rng.uniform(size=(4,3))
print(f6)


[[0.91693121 0.65713274]
 [0.95313518 0.75252398]
 [0.85983215 0.27610646]]
[[0.68235186 0.05382102]
 [0.22035987 0.18437181]
 [0.1759059  0.81209451]]
1
[[1 7 6]
 [1 9 2]
 [3 2 4]]
[[1.35233177 2.69265314 1.06634214]
 [4.97767912 0.04039594 2.66985794]]
[[0.61881018 0.39696833 0.03191712]
 [0.80557437 0.18050622 0.7433831 ]
 [0.15498171 0.81653442 0.87829492]
 [0.61214965 0.7787233  0.16509966]]


In [100]:
# 正規分布に従った乱数
rng = np.random.default_rng(123)
# 平均0, 分散1の分布で出力
x = rng.standard_normal(size=(4,2))
print(x)
# 平均, 標準偏差, 出力数を指定
y = rng.normal(50, 10, 3)
print(y)

[[-0.98912135 -0.36778665]
 [ 1.28792526  0.19397442]
 [ 0.9202309   0.57710379]
 [-0.63646365  0.54195222]]
[46.83404549 46.77610884 50.97167319]


In [109]:
# 同じ要素の数列を作成
a1 = np.zeros(3) # 指定引数分0の入った配列を返す
print(a1)
a2 = np.zeros((2,3)) # 指定行列分0の入った行列を返す
print(a2)
a3 = np.ones(2)# 指定引数分1の入った配列を返す
print(a3)
a4 = np.ones((2,3))# 指定行列分1の入った行列を返す
print(a4)

print("#############")
# 単位行列の作成
a5 = np.eye(3)
print(a5)
print("====指定の値で作成=====")
a6 = np.full((3,3), 3.14) # 第一引数が行列の指定、第二引数が指定値
print(a6)
a7 = np.full((3,3), np.pi) # np.piで円周率を指定できる
print(a7)



[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
#############
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
====指定の値で作成=====
[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]
[[3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]]


### 欠損値 Nan
- Nan: not a number
    - 数値ではないことを宣言
    - ただし、データ型としては、float

In [113]:
# 欠損値の穴埋め Nan
print(np.nan)
a = np.array([1,2, np.nan])
print(a)



nan
[ 1.  2. nan]


In [117]:
# 指定範囲で均等割データを作成
a = np.linspace(0, 1, 5)
print(a)

b = np.linspace(0, np.pi, 21)
print(b)

print("====要素間の差分=====")
c = np.array([2,2,6,1,3])
print(np.diff(c)) # 隣り合う要素の差分を表示


[0.   0.25 0.5  0.75 1.  ]
[0.         0.15707963 0.31415927 0.4712389  0.62831853 0.78539816
 0.9424778  1.09955743 1.25663706 1.41371669 1.57079633 1.72787596
 1.88495559 2.04203522 2.19911486 2.35619449 2.51327412 2.67035376
 2.82743339 2.98451302 3.14159265]
====要素間の差分=====
[ 0  4 -5  2]


#### 連結

In [125]:
print("====行列の連結=======")
a = np.array([1,2,3])
b = np.array([2,3,4])
c = np.concatenate([a, b])
print(c)

print("=================")
d1 = np.array([[1,2,3], [2,3,4]])
d2 = np.array([[10],[20]])
d3 = np.concatenate([d1, d2], axis=1) # axisはどの方向で連結するか 0：行方向、1:列方向
print(d3)

print("hstack関数でも同様に列方向に連結")
e1 = np.hstack([d1, d2])
print(e1)
print("vstack関数で行方向に連結")
d4 = np.array([10,20,30])
e2 = np.vstack([d1, d4])
print(e2)

====行列の連結=======
[1 2 3 2 3 4]
[[ 1  2  3 10]
 [ 2  3  4 20]]
hstack関数でも同様に列方向に連結
[[ 1  2  3 10]
 [ 2  3  4 20]]
vstack関数で行方向に連結
[[ 1  2  3]
 [ 2  3  4]
 [10 20 30]]


#### 分割
- hsplit:列方向で分割
    - h = horizontal 水平方向のh
- vsplit:行方向で分割
    - v = vertical 垂直方向のv

In [130]:
print(e2)
first, second = np.hsplit(e2, [2])
print(first)
print(second)
print("=====================")
first1, second1 = np.vsplit(e2, [2])
print(first1)
print(second1)


[[ 1  2  3]
 [ 2  3  4]
 [10 20 30]]
[[ 1  2]
 [ 2  3]
 [10 20]]
[[ 3]
 [ 4]
 [30]]
[[1 2 3]
 [2 3 4]]
[[10 20 30]]


#### 転置
- m×n行列をn×m行列に変換する

In [131]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
a2 = a.T # <- 転置
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


#### 次元追加
- newaxis or reshapeで追加できる
    - newaxisは要素数の指定は必要ない
    - reshapeでは要素数の指定が必要

In [134]:
a = np.array([1,2,3])
print(a)
a2 = a[np.newaxis, :] # <-行方向へ次元を増やす
print(a2)
a3 = a[:, np.newaxis] # <- 列方向へ次元を増やす
print(a3)

[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]


#### グリッドデータの生成

In [138]:
m = np.arange(0, 4)
print(m)
n = np.arange(4,7)
print(n)
print("=======")
xx, yy = np.meshgrid(m, n)
print(xx) # 第一引数 m を行方向に　第二引数 nの配列の長さ分コピーされる
print("=======")
print(yy) # 第二引数 n を列方向に 第一引数 m の配列の長さ分コピー

[0 1 2 3]
[4 5 6]
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]]


#### Numpyの各機能の確認

In [140]:
a = np.arange(3)
b = np.arange(-3,3).reshape((2,3))
c = np.arange(1,7).reshape((2,3))
d = np.arange(6).reshape((3,2))
e = np.linspace(-1,1,10)
print(a)
print(b)
print(c)
print(d)
print(e)
print("==================")
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
print(e.shape)


[0 1 2]
[[-3 -2 -1]
 [ 0  1  2]]
[[1 2 3]
 [4 5 6]]
[[0 1]
 [2 3]
 [4 5]]
[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
(3,)
(2, 3)
(2, 3)
(3, 2)
(10,)


#### Numpyユニバーサルファンクション
- 配列要素内のデータを一括で変換してくれる

In [142]:
# 配列要素の絶対値を返す処理：通常実装
li = [[-3,-2,-1],[0,1,2]]
new = []
for i, j in enumerate(li):
    new.append([])
    for k in j:
        new[i].append(abs(k))
print(new)

# NumPyを用いた実装
numpy_new = np.abs(b)
print(numpy_new)

[[3, 2, 1], [0, 1, 2]]
[[3 2 1]
 [0 1 2]]


In [157]:
print(e)
print("sin関数の実行") # 正弦
print(np.sin(e))
print("cos関数の実行") # 余弦
print(np.cos(e))

print("======================")
# -infと警告が発生　-infはマイナス無限大を意味
print(np.log(a))
print("#########")
print(np.log10(c)) 
print("#########")
print(np.exp(a)) # eのx乗を表現




[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
sin関数の実行
[-0.84147098 -0.70169788 -0.52741539 -0.3271947  -0.11088263  0.11088263
  0.3271947   0.52741539  0.70169788  0.84147098]
cos関数の実行
[0.54030231 0.71247462 0.84960756 0.94495695 0.99383351 0.99383351
 0.94495695 0.84960756 0.71247462 0.54030231]
[      -inf 0.         0.69314718]
#########
[[0.         0.30103    0.47712125]
 [0.60205999 0.69897    0.77815125]]
#########
[1.         2.71828183 7.3890561 ]


/var/folders/17/mtb1r9zn3xq7qsb6zy36_1b40000gn/T/ipykernel_72153/2963882507.py:9: RuntimeWarning: divide by zero encountered in log
  print(np.log(a))


In [165]:
# ブロードキャスト
a2 = a + 10
print(a)
print(a2)
print("############")
print(a)
print(b)
a3 = a + b
print(a3)
print("############")
ax = a[:, np.newaxis]
print(a)
print(ax)
a4 = a + ax
print(a4)

[0 1 2]
[10 11 12]
############
[0 1 2]
[[-3 -2 -1]
 [ 0  1  2]]
[[-3 -1  1]
 [ 0  2  4]]
############
[0 1 2]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [171]:
print(c)
cx= np.mean(c)
print(cx)
c1 = c - cx
print(c1)
print("##################")
print(b)
print(b*2)
print(b**3)

[[1 2 3]
 [4 5 6]]
3.5
[[-2.5 -1.5 -0.5]
 [ 0.5  1.5  2.5]]
##################
[[-3 -2 -1]
 [ 0  1  2]]
[[-6 -4 -2]
 [ 0  2  4]]
[[-27  -8  -1]
 [  0   1   8]]


In [179]:
# 形状の異なる要素同士の計算
print(a)
print(b)
print(c)
print("##############")
print(b -a)
print("##############")
print(a*b)
print("##############")
print(a / c)
print(c / a)
print("infを出さないようにするために微妙な数値を足すという小技があります")
print(c / (a + 1e-6))



[0 1 2]
[[-3 -2 -1]
 [ 0  1  2]]
[[1 2 3]
 [4 5 6]]
##############
[[-3 -3 -3]
 [ 0  0  0]]
##############
[[ 0 -2 -2]
 [ 0  1  4]]
##############
[[0.         0.5        0.66666667]
 [0.         0.2        0.33333333]]
[[inf 2.  1.5]
 [inf 5.  3. ]]
infを出さないようにするために微妙な数値を足すという小技があります
[[1.00000000e+06 1.99999800e+00 1.49999925e+00]
 [4.00000000e+06 4.99999500e+00 2.99999850e+00]]


/var/folders/17/mtb1r9zn3xq7qsb6zy36_1b40000gn/T/ipykernel_72153/4233592555.py:11: RuntimeWarning: divide by zero encountered in divide
  print(c / a)


In [186]:
# 配列の掛け算
print(a)
print(b)
print("#############")
x1 = np.dot(b, a)
x2 = b @ a # ver3.5以降はこちらも利用可能
print(x1)
print(x2)

# 配列の掛け算は行列の形状が大切、行列の形式が不敵だった場合は、ValueErrorが発生
print("#####################")
print(b)
print(d)
print(b @ d)
print(d @ b)

[0 1 2]
[[-3 -2 -1]
 [ 0  1  2]]
#############
[-4  5]
[-4  5]
#####################
[[-3 -2 -1]
 [ 0  1  2]]
[[0 1]
 [2 3]
 [4 5]]
[[ -8 -14]
 [ 10  13]]
[[  0   1   2]
 [ -6  -1   4]
 [-12  -3   6]]


In [202]:
# 真偽値
print(a)
print(b)
x1 = a > 1 # 配列の各要素についてTrue, Falseを判定して、格納した配列を作成
x2 = b > 0
print(x1)
print(x2)
# True: 1, False:0なので、0でない数をカウントすればOK
print(f"trueの数をカウントします:{np.count_nonzero(x2)}")
print(f"np.sumでも同様の結果が得られます:{np.sum(x2)}")

print(f"np.anyでTrueの存在を確認します{np.any(x2)}")
print(f"np.allで全ての要素がTrueかを確認:{np.all(x2)}")

# 新規配列を作成
new_b = b[b>0] # 0以上の要素だけを抽出して新規配列作成
print(new_b)
print("配列同士の比較")
print(a)
print(b)
print(c)
print(b == c) 
print(a == b) # 形状が異なる場合はブロードキャストされて形状を揃えて実行される
print("#################")
print((b == c)| (a == b))
new_array = b[(b==c)|(a==b)]
print(new_array)


[0 1 2]
[[-3 -2 -1]
 [ 0  1  2]]
[False False  True]
[[False False False]
 [False  True  True]]
trueの数をカウントします:2
np.sumでも同様の結果が得られます:2
np.anyでTrueの存在を確認しますTrue
np.allで全ての要素がTrueかを確認:False
[1 2]
配列同士の比較
[0 1 2]
[[-3 -2 -1]
 [ 0  1  2]]
[[1 2 3]
 [4 5 6]]
[[False False False]
 [False False False]]
[[False False False]
 [ True  True  True]]
#################
[[False False False]
 [ True  True  True]]
[0 1 2]


In [205]:
print(b)
print(c)
x = np.allclose(b, c)
print(f"np.allcloseは要素の判定ではなく誤差の範囲内の判定化を確認しています::{x}")
x2 = np.allclose(b, c, atol=10.0)
print(f"誤差を指定すると結果が変わります:{x2}")

[[-3 -2 -1]
 [ 0  1  2]]
[[1 2 3]
 [4 5 6]]
np.allcloseは要素の判定ではなく誤差の範囲内の判定化を確認しています::False
誤差を指定すると結果が変わります:True
