In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
# printをつけるとarray表記でなくなる
print(a)
# typeはndarray objectになります
print(type(a))
# 1次元配列3要素であることがわかる
a.shape

[1 2 3]
<class 'numpy.ndarray'>


(3,)

In [7]:
# 2次元配列を指定
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# 2×3行列であることが読み取れる
b.shape

(2, 3)

In [12]:
c1 = np.array([0,1,2,3,4,5])
# 変形(a×b行列に変換)
c2 = c1.reshape((2,3))
# reshapeは要素数が重要 = 要素数が合わない場合はエラーになります
# c2 = c1.reshape((3,4)) <- これはダメ
c2

array([[0, 1, 2],
       [3, 4, 5]])

#### 参照とコピー
- ravel:参照
- flatten:コピー

- 参照は変数に代入されたオブジェクトのメモリ上のアドレスを指します。
- コピーとは変数に代入されたオブジェクトを複製して新しいオブジェクトを作成することを指します。
- python標準のリストではスライスした結果はコピーが渡される
- Numpyでは、スライスの結果は参照が渡されるので注意！
- Pythonの標準リスト型では浅いコピーと深いコピーが区別される
- Numpyのcopyメソッドはオブジェクトを別に生成するので標準の深いコピーと同値であるとわかる

#### 浅いコピー　深いコピー
- pythonには2種類のコピーが存在
- 浅いコピー
    - オブジェクトのコピーを作成しますが、コピーされたオブジェクトの内部に含まれる他のオブジェクトについては、参照がコピー
    - 『深いコピー』とは、オブジェクトのコピーをすべて作成します。

In [13]:
# ravelメソッドは1次元配列に変換するメソッド
c3 = c2.ravel()
c3

array([0, 1, 2, 3, 4, 5])

In [14]:
c4 = c2.flatten()
c4

array([0, 1, 2, 3, 4, 5])

In [19]:
# 浅いコピー
import copy
a = [1, 2, [3, 4, 5]]
b = a.copy()
print("1,2は新規オブジェクトが生成されるが[3,4,5]については、参照として複製")
print(a)
print(b)
# 深いコピー
c = copy.deepcopy(a)
print("deepcopyは全く同じオブジェクトを生成します")
print(a)
print(c)

1,2は新規オブジェクトが生成されるが[3,4,5]については、参照として複製
[1, 2, [3, 4, 5]]
[1, 2, [3, 4, 5]]
deepcopyは全く同じオブジェクトを生成します
[1, 2, [3, 4, 5]]
[1, 2, [3, 4, 5]]


In [69]:
a = np.array([1,2,3])
print(a)
# インデックスを指定してその要素を変更することができる
a[2] = 4
print(a)

b = np.array([[1,2,3],[4,5,6]])
print(b)
b[1,2] = 7 # 2行目の3番目の要素を置き換える
print(b)

[1 2 3]
[1 2 4]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 7]]


In [71]:
# 参照
a = np.array([1,2,3])
a1 = a
print(a1, a)
a1[1] = 5
# aの値を変えていないのにどちらの要素も変更されている
print(a1, a)

[1 2 3] [1 2 3]
[1 5 3] [1 5 3]


In [72]:
# コピー
a = np.array([1,2,3])
a2 = a.copy()
print(a2, a)
a2[0] = 100
# copyで生成したa2の値を変更してもaの行列はそのままになっている
print(a2, a)

[1 2 3] [1 2 3]
[100   2   3] [1 2 3]


In [74]:
c2 = np.array([[0,1,2],[3,4,5]])
c3 = c2.ravel()
c4 = c2.flatten()
print(c2, c3)
print(c2, c4)
c3[0] = 100 # c2をravelで1次元に戻したものは参照なので、元の行列に影響
c4[0] = 200 # c2をflattenで1次元に戻したものはコピーなので、元の行列に影響しない
print(c2, c3)
print(c2, c4)


[[0 1 2]
 [3 4 5]] [0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]] [0 1 2 3 4 5]
[[100   1   2]
 [  3   4   5]] [100   1   2   3   4   5]
[[100   1   2]
 [  3   4   5]] [200   1   2   3   4   5]


In [78]:
py_list1 = [0,1]
py_list2 = py_list1[:] # python標準のスライスはコピー
print(py_list1, py_list2)
py_list2[0] = 20
print(py_list1, py_list2)

print("=======================")
np_array1 = np.array([0,1])
np_array2 = np_array1[:] # Numpyのスライスは参照として生成
print(np_array1, np_array2)
np_array2[0] = 100
print(np_array1, np_array2)


[0, 1] [0, 1]
[0, 1] [20, 1]
[0 1] [0 1]
[100   1] [100   1]


In [21]:
a = np.array([1,2,3])
# windowsはnp.int32 linuxはnp.int64が割り当てられる
a.dtype

dtype('int64')

In [25]:
d = np.array([1,2], dtype=np.int16)
d.dtype


dtype('int16')

In [26]:
d.astype(np.float16)


array([1., 2.], dtype=float16)

In [28]:
# numpyの配列でもスライスは活用することができる
print(a)
print(a[0])
print(a[1:])
print(a[:-1])


[1 2 3]
1
[2 3]
[1 2]


In [67]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b[0])
print(b[1,0])
print(b[:2]) # <- この書き方だと普通のスライス
print(b[:,2])# <- ,2にすると全ての行の3番目の要素を抽出
print(b[1:])# <- 
print("#######")
print(b[2,:])# <- 2, = 2, = 2番目の行 = [7,8,9] :=全ての要素
# print(b[1,:,1]) <-　この指定方法は誤り
print("######")
print(b[0,1:]) # <- 0, = 0番目の行 = [1,2,3] 1: = 2つ目の要素以降
print(b[1: ,1]) # <- 1: = 1番目の行から最後の行 = [4,5,6],[7,8,9] ,1 = 各行の1番目 = 5,8
print("###################")
print(b[:,[0,2]]) # <- : = 全ての行 [0,2] = 1番目の要素と3番目の要素を取得


[1 2 3]
4
[[1 2 3]
 [4 5 6]]
[3 6 9]
[[4 5 6]
 [7 8 9]]
#######
[7 8 9]
######
[2 3]
[5 8]
###################
[[1 3]
 [4 6]
 [7 9]]
