In [1]:
import numpy as np

In [28]:
# 1次元配列の生成
sample1 = np.array([1,2,3])
print(sample1.shape)
print(type(sample1))
print(sample1.astype)
print(sample1.dtype)
print(f"printで出力するとarray配列表示ではなくなります:{sample1}")
sample1

(3,)
<class 'numpy.ndarray'>
<built-in method astype of numpy.ndarray object at 0x10aec85d0>
int64
printで出力するとarray配列表示ではなくなります:[1 2 3]


array([1, 2, 3])

In [29]:
# 2次元配列を指定
sample2 = np.array([[1,2,3],[4,5,6]])
print(sample2.shape)
print(type(sample2))
print(sample2.astype)
print(sample2.dtype)
sample2

(2, 3)
<class 'numpy.ndarray'>
<built-in method astype of numpy.ndarray object at 0x10b41e9d0>
int64


array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b[0])
print(b[1,0])
print(b[:2]) # <- この書き方だと普通のスライス
print(b[:,2])# <- ,2にすると全ての行の3番目の要素を抽出
print(b[1:])# <- 
print("#######")
print(b[2,:])# <- 2, = 2, = 2番目の行 = [7,8,9] :=全ての要素
# print(b[1,:,1]) <-　この指定方法は誤り
print("######")
print(b[0,1:]) # <- 0, = 0番目の行 = [1,2,3] 1: = 2つ目の要素以降
print(b[1: ,1]) # <- 1: = 1番目の行から最後の行 = [4,5,6],[7,8,9] ,1 = 各行の1番目 = 5,8
print("###################")
print(b[:,[0,2]]) # <- : = 全ての行 [0,2] = 1番目の要素と3番目の要素を取得


[1 2 3]
4
[[1 2 3]
 [4 5 6]]
[3 6 9]
[[4 5 6]
 [7 8 9]]
#######
[7 8 9]
######
[2 3]
[5 8]
###################
[[1 3]
 [4 6]
 [7 9]]


### 行列の変換
- reshape(a, b)を利用すると(a×b行列に変換できる)
- 行列のどちらかを-1と設定すると、設定していないもう片方の方にうまく次元数を合わせてくれる
- ただし、設定する次元数が合わない場合は行列両方指定、-1を利用した指定どちらもエラーになってしまいます

In [21]:
sample3 = np.array([0,1,2,3,4,5])
reshape1 = sample3.reshape(2,3)
# reshape_out = sample3.reshape(5,2) <- こちらは次元数が適切に分割できないためエラー
reshape2 = sample3.reshape(3,-1)
reshape3 = sample3.reshape(-1, 3)
# reshape4 = sample3.reshape(-1, 4) <- こちらは次元数が適切に分割できないためエラー
print(sample3)
print(reshape1)
print(reshape2)
print(reshape3)


[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]
[[0 1 2]
 [3 4 5]]


### 参照とコピー
- 参照は変数に代入されたメモリ上のアドレスを渡す
    - 「ravel」を利用する
    - numpyもスライスを利用できるが、スライスを利用した場合は参照が渡される
- コピーは変数に代入されたオブジェクトを複製して新しいオブジェクトを作成
    - 「flatten」を利用する
    - python標準リストのスライス([x:y])はコピーを渡す

### 浅いコピーと深いコピー
- 浅いコピー
    - オブジェクトのコピーを作成するが、コピーされたオブジェクトの内部に含まれる他のオブジェクトは参照が渡される
- 深いコピー
    - オブジェクトの全てのコピーを作成する
- 場合わけ
    - Pythonの標準リスト型では、浅いコピーと深いコピーが区別
    - Numpyのcopyメソッドでは、オブジェクトを別に生成するので、深いコピーとなる


In [23]:
sample4 = np.array([0,1,2,3,4,5])
# 参照
ravel1 = sample4.ravel()
ravel1[1] = 100

# 参照渡しであるため、ravelの特定の要素の更新がsample4にも影響している
print(sample4)
print(ravel1)


[  0 100   2   3   4   5]
[  0 100   2   3   4   5]


In [25]:
sample5 = np.array([0,1,2,3,4,5])
# copy
flatten1 = sample5.flatten()
flatten1[1] = 100

# copyであるため、元の要素に影響を与えない
print(sample5)
print(flatten1)


[0 1 2 3 4 5]
[  0 100   2   3   4   5]


In [27]:
py_list1 = [0,1]
py_list2 = py_list1[:] # python標準のスライスはコピー
print(py_list1, py_list2)
py_list2[0] = 20
print(py_list1, py_list2)

print("=======================")
np_array1 = np.array([0,1])
np_array2 = np_array1[:] # Numpyのスライスは参照として生成
print(np_array1, np_array2)
np_array2[0] = 100
print(np_array1, np_array2)


[0, 1] [0, 1]
[0, 1] [20, 1]
[0 1] [0 1]
[100   1] [100   1]


In [26]:
# 浅いコピー
import copy
a = [1, 2, [3, 4, 5]]
b = a.copy()
print("1,2は新規オブジェクトが生成されるが[3,4,5]については、参照として複製")
print(a)
print(b)
# 深いコピー
c = copy.deepcopy(a)
print("deepcopyは全く同じオブジェクトを生成します")
print(a)
print(c)

1,2は新規オブジェクトが生成されるが[3,4,5]については、参照として複製
[1, 2, [3, 4, 5]]
[1, 2, [3, 4, 5]]
deepcopyは全く同じオブジェクトを生成します
[1, 2, [3, 4, 5]]
[1, 2, [3, 4, 5]]


### さまざまなnumpyの変数生成方法
- arange
    - arange(x):0~x-1までの要素を生成
    - arange(x,y):x~y-1までの要素を生成
    - arange(x,y,z):x~y-1までの要素をzずつ加算して生成
- random
    - 要素を指定範囲でrandomに生成
- zeros
    - zeros(x):指定引数分0の入った配列を生成
    - zeros(2,3):指定行列分の0の入った行列を生成
- ones
    - zerosと同じ指定方法で、1の入った配列を返す
- eye
    - eye(x):x×xの単位行列を作成
- full
    - full((x,y), z):第一引数で設定した次元数に第二引数分を入れた配列を生成
- linspace
    - linspace(x,y,z):第一、第二引数の要素をz(均等割)したデータを作成


In [31]:
sample1 = np.arange(10)
sample2 = np.arange(1,11)
sample3 = np.arange(1,11,2)
print(sample1)
print(sample2)
print(sample3)

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [32]:
# random数値を返す
# 旧式generator, 最新generatorがありますが、今回は最新の方をレクチャー
rng = np.random.default_rng() # <- object生成
f = rng.random((3,2)) # m行 * n列という指定で 0<= x < 1までの数値を返す

rng2 = np.random.default_rng(123) # seed値を設定することで、randomで返却される値を固定できる
f2 = rng2.random((3,2))
print(f)
print(f2)

# 特定の範囲内の数値を生成
rng3 = np.random.default_rng(123)
f3 = rng3.integers(1,10) # 指定した範囲の数値から1つの値を返す
print(f3)

rng4 = np.random.default_rng(123)
# 第一引数、第二引数は省略可 default 0.0 <= x < 1.0
f4 = rng4.integers(1, 10, size=(3,3)) # 第一引数 <= x < 第二引数未満　でランダム整数値を size keyword引数でタプルを渡した行と列を生成
print(f4)

rng5 = np.random.default_rng(123)
# uniformを設定すると返却値がfloatになる
f5 = rng.uniform(0.0, 5.0, size=(2,3))
print(f5)
f6 = rng.uniform(size=(4,3))
print(f6)


[[0.61101598 0.11724823]
 [0.26687715 0.75011105]
 [0.87899344 0.63418201]]
[[0.68235186 0.05382102]
 [0.22035987 0.18437181]
 [0.1759059  0.81209451]]
1
[[1 7 6]
 [1 9 2]
 [3 2 4]]
[[3.64016952 3.83323819 0.03625096]
 [3.46839922 0.37199485 3.5077716 ]]
[[0.44903672 0.54099488 0.09767262]
 [0.02065486 0.18914437 0.83910443]
 [0.12122531 0.33071081 0.03499905]
 [0.82767899 0.55325528 0.34066084]]


In [33]:
# 正規分布に従った乱数
rng = np.random.default_rng(123)
# 平均0, 分散1の分布で出力
x = rng.standard_normal(size=(4,2))
print(x)
# 平均, 標準偏差, 出力数を指定
y = rng.normal(50, 10, 3)
print(y)

[[-0.98912135 -0.36778665]
 [ 1.28792526  0.19397442]
 [ 0.9202309   0.57710379]
 [-0.63646365  0.54195222]]
[46.83404549 46.77610884 50.97167319]


In [34]:
# 同じ要素の数列を作成
a1 = np.zeros(3) # 指定引数分0の入った配列を返す
print(a1)
a2 = np.zeros((2,3)) # 指定行列分0の入った行列を返す
print(a2)
a3 = np.ones(2)# 指定引数分1の入った配列を返す
print(a3)
a4 = np.ones((2,3))# 指定行列分1の入った行列を返す
print(a4)

print("#############")
# 単位行列の作成
a5 = np.eye(3)
print(a5)
print("====指定の値で作成=====")
a6 = np.full((3,3), 3.14) # 第一引数が行列の指定、第二引数が指定値
print(a6)
a7 = np.full((3,3), np.pi) # np.piで円周率を指定できる
print(a7)



[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
#############
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
====指定の値で作成=====
[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]
[[3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]]


In [36]:
# 指定範囲で均等割データを作成
a = np.linspace(0, 1, 5)
print(a)

b = np.linspace(0, np.pi, 21)
print(b)

print("====要素間の差分=====")
c = np.array([2,2,6,1,3])
print(np.diff(c)) # 隣り合う要素の差分を表示


[0.   0.25 0.5  0.75 1.  ]
[0.         0.15707963 0.31415927 0.4712389  0.62831853 0.78539816
 0.9424778  1.09955743 1.25663706 1.41371669 1.57079633 1.72787596
 1.88495559 2.04203522 2.19911486 2.35619449 2.51327412 2.67035376
 2.82743339 2.98451302 3.14159265]
====要素間の差分=====
[ 0  4 -5  2]


### 欠損値
- Nan(not a number)で表現される。
    - 数値ではないことを宣言
    - ただし、データ型としてはfloat型となっている


In [35]:
# 欠損値の穴埋め Nan
print(np.nan)
a = np.array([1,2, np.nan])
print(a)

nan
[ 1.  2. nan]


### 連結と分割
- 連結
    - axis=0, vstack:行方向↓
        - vはvertical(垂直)
    - axis=1, hstack:列方向→
        - hはhorizontal(水平)
- 分割
    - vsplit:行方向分割
    - hsplit:列方向分割


In [38]:
print("====行列の連結=======")
a = np.array([1,2,3])
b = np.array([2,3,4])
c = np.concatenate([a, b])
print(c)

print("=================")
d1 = np.array([[1,2,3], [2,3,4]])
d2 = np.array([[10],[20]])
d3 = np.concatenate([d1, d2], axis=1) # axisはどの方向で連結するか 0：行方向、1:列方向
print(d3)

print("hstack関数でも同様に列方向に連結")
e1 = np.hstack([d1, d2])
print(e1)
print("vstack関数で行方向に連結")
d4 = np.array([10,20,30])
e2 = np.vstack([d1, d4])
print(e2)

====行列の連結=======
[1 2 3 2 3 4]
[[ 1  2  3 10]
 [ 2  3  4 20]]
hstack関数でも同様に列方向に連結
[[ 1  2  3 10]
 [ 2  3  4 20]]
vstack関数で行方向に連結
[[ 1  2  3]
 [ 2  3  4]
 [10 20 30]]


In [39]:
print(e2)
first, second = np.hsplit(e2, [2])
print(first)
print(second)
print("=====================")
first1, second1 = np.vsplit(e2, [2])
print(first1)
print(second1)


[[ 1  2  3]
 [ 2  3  4]
 [10 20 30]]
[[ 1  2]
 [ 2  3]
 [10 20]]
[[ 3]
 [ 4]
 [30]]
[[1 2 3]
 [2 3 4]]
[[10 20 30]]


### 転置
- m×n行列をn×m行列へ変換


In [40]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
a2 = a.T # <- 転置
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### 次元追加
- newaxis or reshapeで追加できる
    - newaxisは要素数の指定は必要ない
    - reshapeでは要素数の指定が必要

In [41]:
a = np.array([1,2,3])
print(a)
a2 = a[np.newaxis, :] # <-行方向へ次元を増やす
print(a2)
a3 = a[:, np.newaxis] # <- 列方向へ次元を増やす
print(a3)

[1 2 3]
[[1 2 3]]
[[1]
 [2]
 [3]]


In [42]:
m = np.arange(0, 4)
print(m)
n = np.arange(4,7)
print(n)
print("=======")
xx, yy = np.meshgrid(m, n)
print(xx) # 第一引数 m を行方向に　第二引数 nの配列の長さ分コピーされる
print("=======")
print(yy) # 第二引数 n を列方向に 第一引数 m の配列の長さ分コピー

[0 1 2 3]
[4 5 6]
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]]


### ユニバーサルファンクション
- 配列要素ないのデータを一括変換


In [43]:
# 配列要素の絶対値を返す処理：通常実装
li = [[-3,-2,-1],[0,1,2]]
new = []
for i, j in enumerate(li):
    new.append([])
    for k in j:
        new[i].append(abs(k))
print(new)

# NumPyを用いた実装
numpy_new = np.abs(b)
print(numpy_new)

[[3, 2, 1], [0, 1, 2]]
[2 3 4]


### その他の変数生成
- cos
- sin
- log
- log10
- exp

In [45]:
e = np.linspace(-1,1,10)
print(e)
print("sin関数の実行") # 正弦
print(np.sin(e))
print("cos関数の実行") # 余弦
print(np.cos(e))

print("======================")
# -infと警告が発生　-infはマイナス無限大を意味
print(np.log(a))
print("#########")
print(np.log10(c)) 
print("#########")
print(np.exp(a)) # eのx乗を表現




[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
sin関数の実行
[-0.84147098 -0.70169788 -0.52741539 -0.3271947  -0.11088263  0.11088263
  0.3271947   0.52741539  0.70169788  0.84147098]
cos関数の実行
[0.54030231 0.71247462 0.84960756 0.94495695 0.99383351 0.99383351
 0.94495695 0.84960756 0.71247462 0.54030231]
[0.         0.69314718 1.09861229]
#########
[0.         0.30103    0.47712125 0.30103    0.47712125 0.60205999]
#########
[ 2.71828183  7.3890561  20.08553692]


In [46]:
# ブロードキャスト
a2 = a + 10
print(a)
print(a2)
print("############")
print(a)
print(b)
a3 = a + b
print(a3)
print("############")
ax = a[:, np.newaxis]
print(a)
print(ax)
a4 = a + ax
print(a4)

[1 2 3]
[11 12 13]
############
[1 2 3]
[2 3 4]
[3 5 7]
############
[1 2 3]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [49]:
a = np.arange(3)
b = np.arange(-3,3).reshape((2,3))
c = np.arange(1,7).reshape((2,3))
d = np.arange(6).reshape((3,2))
e = np.linspace(-1,1,10)
# 配列の掛け算
print(a)
print(b)
print("#############")
x1 = np.dot(b, a)
x2 = b @ a # ver3.5以降はこちらも利用可能
print(x1)
print(x2)

# 配列の掛け算は行列の形状が大切、行列の形式が不敵だった場合は、ValueErrorが発生
print("#####################")
print(b)
print(d)
print(b @ d)
print(d @ b)

[0 1 2]
[[-3 -2 -1]
 [ 0  1  2]]
#############
[-4  5]
[-4  5]
#####################
[[-3 -2 -1]
 [ 0  1  2]]
[[0 1]
 [2 3]
 [4 5]]
[[ -8 -14]
 [ 10  13]]
[[  0   1   2]
 [ -6  -1   4]
 [-12  -3   6]]


In [51]:
# 真偽値
print(a)
print(b)
x1 = a > 1 # 配列の各要素についてTrue, Falseを判定して、格納した配列を作成
x2 = b > 0
print(x1)
print(x2)
# True: 1, False:0なので、0でない数をカウントすればOK
print(f"trueの数をカウントします:{np.count_nonzero(x2)}")
print(f"np.sumでも同様の結果が得られます:{np.sum(x2)}")

print(f"np.anyでTrueの存在を確認します{np.any(x2)}")
print(f"np.allで全ての要素がTrueかを確認:{np.all(x2)}")

# 新規配列を作成
new_b = b[b>0] # 0以上の要素だけを抽出して新規配列作成
print(new_b)
print("配列同士の比較")
print(a)
print(b)
print(c)
print(b == c) 
print(a == b) # 形状が異なる場合はブロードキャストされて形状を揃えて実行される
print("#################")
print((b == c)| (a == b))
new_array = b[(b==c)|(a==b)]
print(new_array)

print(b)
print(c)
x = np.allclose(b, c)
print(f"np.allcloseは要素の判定ではなく誤差の範囲内の判定化を確認しています::{x}")
x2 = np.allclose(b, c, atol=10.0)
print(f"誤差を指定すると結果が変わります:{x2}")


[0 1 2]
[[-3 -2 -1]
 [ 0  1  2]]
[False False  True]
[[False False False]
 [False  True  True]]
trueの数をカウントします:2
np.sumでも同様の結果が得られます:2
np.anyでTrueの存在を確認しますTrue
np.allで全ての要素がTrueかを確認:False
[1 2]
配列同士の比較
[0 1 2]
[[-3 -2 -1]
 [ 0  1  2]]
[[1 2 3]
 [4 5 6]]
[[False False False]
 [False False False]]
[[False False False]
 [ True  True  True]]
#################
[[False False False]
 [ True  True  True]]
[0 1 2]
[[-3 -2 -1]
 [ 0  1  2]]
[[1 2 3]
 [4 5 6]]
np.allcloseは要素の判定ではなく誤差の範囲内の判定化を確認しています::False
誤差を指定すると結果が変わります:True


NumPyには、配列用の `ndarray` と行列用の `matrix` があります。

### 配列用の `ndarray`

```python
import numpy as np

a = np.array([[1, 2], [3, 4]])
print(type(a))  # 出力: <class 'numpy.ndarray'>
```
### 行列用の`matrix`
```python
b = np.matrix([[1, 2], [3, 4]])
print(type(b))  # 出力: <class 'numpy.matrix'>
```

### 違い
- どちらも同じ形状だが、`matrix`は行列として定義される
    - ndarray a*aは要素ごとの積
    - matrix b*bは行列の積

In [52]:
# ndarrayとmatrix
import numpy as np

a = np.array([[1, 2], [3, 4]])
result_ndarray = a * a
print(result_ndarray)  # 出力: [[ 1  4]
                        #      [ 9 16]]

b = np.matrix([[1, 2], [3, 4]])
result_matrix = b * b
print(result_matrix)  # 出力: [[ 7 10]
                       #      [15 22]]


[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [53]:
# dotの取り方 ベクトルの内積を取るためのメソッド
a = np.array([1, 1])

b = np.array([2, 2])

c = np.array([[3, 3], 
              [4, 4]])

d = np.array([[5, 5], 
              [6, 6], 
              [7, 7]])

print(a * b)
print(np.dot(a, b))
print(np.dot(c, b))

[2 2]
4
[12 16]
